// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNQzy9vWLCXCYORlfJAJFn6Fvm8SxKg9M',
    appId: '1:372027806126:web:c0438f1cc106df6640f83f',
    messagingSenderId: '372027806126',
    projectId: 'fir-retail-hub-2ce37',
    authDomain: 'fir-retail-hub-2ce37.firebaseapp.com',
    storageBucket: 'fir-retail-hub-2ce37.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMi7ihOoJQreXsF2sZXP7tm3U-LgKop5M',
    appId: '1:372027806126:android:9ca9edd21b9e2c6c40f83f',
    messagingSenderId: '372027806126',
    projectId: 'fir-retail-hub-2ce37',
    storageBucket: 'fir-retail-hub-2ce37.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtBM0qyZgbttJM36eg_hW2FNBO-CQnGnw',
    appId: '1:372027806126:ios:e9a3b7d8b6fbe62e40f83f',
    messagingSenderId: '372027806126',
    projectId: 'fir-retail-hub-2ce37',
    storageBucket: 'fir-retail-hub-2ce37.firebasestorage.app',
    iosBundleId: 'com.example.foodika',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtBM0qyZgbttJM36eg_hW2FNBO-CQnGnw',
    appId: '1:372027806126:ios:e9a3b7d8b6fbe62e40f83f',
    messagingSenderId: '372027806126',
    projectId: 'fir-retail-hub-2ce37',
    storageBucket: 'fir-retail-hub-2ce37.firebasestorage.app',
    iosBundleId: 'com.example.foodika',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNQzy9vWLCXCYORlfJAJFn6Fvm8SxKg9M',
    appId: '1:372027806126:web:38274fb6df5c9f6f40f83f',
    messagingSenderId: '372027806126',
    projectId: 'fir-retail-hub-2ce37',
    authDomain: 'fir-retail-hub-2ce37.firebaseapp.com',
    storageBucket: 'fir-retail-hub-2ce37.firebasestorage.app',
  );

}